### ISSUE TITLE
Screenshot in the README

### ISSUE THREAD

**Issue by KathleenLD** [jlord/sheetsee-pocket#1]
The screenshot in the README.md doesn't seem to be pointing to anything :(

**Comment by jlord** [comment]
Do you mean like a link? It's not a link, just a preview of what the site looks like :)

At that time there was no live site to view either, you'd have to deploy it locally. I've just switched it over to client-side so it's live now, yay! [jlord.github.io/sheetsee-pocket](jlord.github.io/sheetsee-pocket)

**Comment by KathleenLD** [comment]
Oh, I see what was happening. For some reason the screencap you'd put at the top of the readme wasn't rendering. It's there now. 

Thanks!!
