### ISSUE TITLE
Auto-update site after saving to Pocket archive

### ISSUE THREAD

**Issue by nickfrost** [jlord/sheetsee-pocket#5]
I'm not sure how to have my sheet site update once I've added more links to Pocket archive. The process is all set up and the page is at http://nickfrost.github.io/sheetsee-pocket/. 

Am I missing something or will the site update by itself in time intervals or?  

Thanks!

Nick

**Comment by jlord** [comment]
Hi!

Yeah the data in the spreadsheet shoud update on its own through If This Than That. Sometimes that takes a few minutes, sometimes 10s of minutes. Whenever you go to your site you should see the latest from the spreadsheet.

**Comment by nickfrost** [comment]
I fixed it. Somehow IFTTT had created another spreadsheet, so I loaded it with data and it's working now. This is such a cool project, btw!! Thanks :)

**Comment by jlord** [comment]
Yay :tada: Thanks!
